name: Docker pipeline

trigger:
- master
- feature/*

pool: my-pool

variables: 
- group: docker-vars

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
    - script: docker build -t avishaihorovicz/weight-app-tracker:latest .
      displayName: Build an image
    
    - script: docker push avishaihorovicz/weight-app-tracker:latest
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
      displayName: Push the image to ther docker hub repository

