name: Docker pipeline

trigger:
- master
- feature/*

pool: my-pool


stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
    - script: docker build -t $(registry_url)/weight-tracker:latest .
      displayName: Build an image

    - script: docker login -u $(registry_username) -p $(registry_password) $(registry_url)
      displayName: connect to azure container registry
    
    - script: docker push urielofir.azurecr.io/weight-tracker:latest
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
      displayName: Push the image to ther docker hub repository

