trigger:
- master

pool:
  my-pool
 
steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
 
- task: CopyFiles@2
  displayName: 'Stage Artifacts'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'


- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'Weight-app-tracker/web-tracker-app'
    vstsFeedPackagePublish: 'web-tracker-artifact'
    versionOption: 'minor'
