
- hosts: all
  become: yes
  gather_facts: no
  
  vars_files:
    - docker-vars
  
  tasks:
  
    - name: Clone a github repository
      git:
         repo: https://github.com/avishoro/CI-CD-with-docker.git
         dest: /home/avishai/bootcamp-app
         force: yes
         clone: yes
         update: yes
        
    - name: connect to Azure container registry
      shell: docker login -u {{registry_username}} -p {{registry_password}} {{registry_url}}
  

    - name: Pull Docker image
      shell: docker pull {{registry_url}}/weight-app-tracker
 

    - name: add .env file
        copy:
          dest: "/home/avishai/bootcamp-app/.env"
          content: |
            # Host configuration
            PORT=8080
            HOST={{host}}
            # Postgres configuration
            PGHOST={{pghost}}
            PGUSERNAME={{pg_username}}
            PGDATABASE=postgres
            PGPASSWORD={{pg_password}}
            PGPORT=5432
            HOST_URL=http://{{LB_ip}}:8080
            COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
            NODE_ENV=development
            # Okta configuration
            OKTA_ORG_URL={{okta_url}}
            OKTA_CLIENT_ID={{okta_client_id}}
            OKTA_CLIENT_SECRET={{okta_client_secret}}
    

    - name: run Docker image
      shell: docker run --restart always -d -p 0.0.0.0:8080:8080/tcp {{registry_url}}/weight-tracker

    - name: copy .env file to docker container
      shell: docker cp ~/.env  $(sudo docker ps -aq):/usr/src/app/.env

    - name: restart docker container
      shell: docker restart $(sudo docker ps -aq)
